// MVP dataset — hand-curated, deliberately small and opinionated.
// Everything the map draws lives here; the component holds no names of its own.

export type Field = "philosophy" | "mathematics" | "physics" | "psychology" | "life";

export type Person = {
  id: string;
  name: string;
  born: number; // negative = BCE
  died: number;
  field: Field;
  also?: Field; // the bridge people — a second home
  one: string; // one line, one idea
};

export type LinkKind = "taught" | "read" | "against" | "with";

export type Link = {
  from: string; // the earlier one
  to: string; // the later one
  kind: LinkKind;
  note?: string;
};

export const FIELDS: { id: Field; label: string; short: string }[] = [
  { id: "philosophy", label: "Philosophy", short: "Phil" },
  { id: "mathematics", label: "Mathematics", short: "Math" },
  { id: "physics", label: "Physics & cosmos", short: "Phys" },
  { id: "psychology", label: "Mind", short: "Mind" },
  { id: "life", label: "Life", short: "Life" },
];

export const PEOPLE: Person[] = [
  // --- ancient ------------------------------------------------------
  { id: "thales", name: "Thales", born: -624, died: -546, field: "philosophy", also: "mathematics", one: "The world can be explained without the gods." },
  { id: "pythagoras", name: "Pythagoras", born: -570, died: -495, field: "mathematics", also: "philosophy", one: "Reality is number and ratio." },
  { id: "heraclitus", name: "Heraclitus", born: -535, died: -475, field: "philosophy", one: "Everything flows; the world is process, not stuff." },
  { id: "parmenides", name: "Parmenides", born: -515, died: -450, field: "philosophy", one: "Change is an illusion; being simply is." },
  { id: "democritus", name: "Democritus", born: -460, died: -370, field: "philosophy", also: "physics", one: "Atoms and void, nothing else." },
  { id: "socrates", name: "Socrates", born: -470, died: -399, field: "philosophy", one: "The question is the method." },
  { id: "plato", name: "Plato", born: -428, died: -348, field: "philosophy", also: "mathematics", one: "Behind appearances lie perfect forms." },
  { id: "aristotle", name: "Aristotle", born: -384, died: -322, field: "philosophy", also: "life", one: "Start from the thing in front of you and classify it." },
  { id: "epicurus", name: "Epicurus", born: -341, died: -270, field: "philosophy", one: "Atoms swerve — and so we are free." },
  { id: "euclid", name: "Euclid", born: -325, died: -265, field: "mathematics", one: "From five axioms, a world." },
  { id: "archimedes", name: "Archimedes", born: -287, died: -212, field: "mathematics", also: "physics", one: "Mathematics applied to levers, water and sand." },
  { id: "ptolemy", name: "Ptolemy", born: 100, died: 170, field: "physics", also: "mathematics", one: "A model that saves the appearances for 1400 years." },

  // --- scientific revolution ---------------------------------------
  { id: "copernicus", name: "Copernicus", born: 1473, died: 1543, field: "physics", one: "Move the Earth and the sky gets simpler." },
  { id: "bacon", name: "Francis Bacon", born: 1561, died: 1626, field: "philosophy", one: "Knowledge grows by experiment, not authority." },
  { id: "galileo", name: "Galileo", born: 1564, died: 1642, field: "physics", one: "The book of nature is written in mathematics." },
  { id: "kepler", name: "Kepler", born: 1571, died: 1630, field: "physics", also: "mathematics", one: "Orbits are ellipses — the circle was a prejudice." },
  { id: "descartes", name: "Descartes", born: 1596, died: 1650, field: "philosophy", also: "mathematics", one: "Doubt everything, then rebuild from the thinking self." },
  { id: "spinoza", name: "Spinoza", born: 1632, died: 1677, field: "philosophy", one: "God and nature are one substance." },
  { id: "pascal", name: "Pascal", born: 1623, died: 1662, field: "mathematics", also: "philosophy", one: "Chance has laws; the heart has reasons." },
  { id: "newton", name: "Newton", born: 1643, died: 1727, field: "physics", also: "mathematics", one: "One law for the apple and the moon." },
  { id: "leibniz", name: "Leibniz", born: 1646, died: 1716, field: "mathematics", also: "philosophy", one: "Calculus, binary, and a universe of monads." },

  // --- the long enlightenment --------------------------------------
  { id: "hume", name: "Hume", born: 1711, died: 1776, field: "philosophy", one: "You never see causation — only one thing, then another." },
  { id: "euler", name: "Euler", born: 1707, died: 1783, field: "mathematics", one: "The language most of mathematics still speaks." },
  { id: "kant", name: "Kant", born: 1724, died: 1804, field: "philosophy", one: "Space and time are how we see, not what is." },
  { id: "gauss", name: "Gauss", born: 1777, died: 1855, field: "mathematics", one: "Curvature belongs to the surface itself." },
  { id: "hegel", name: "Hegel", born: 1770, died: 1831, field: "philosophy", one: "History is an argument working itself out." },
  { id: "schopenhauer", name: "Schopenhauer", born: 1788, died: 1860, field: "philosophy", also: "psychology", one: "Underneath reason: blind will." },
  { id: "faraday", name: "Faraday", born: 1791, died: 1867, field: "physics", one: "Not forces at a distance — fields, everywhere." },
  { id: "darwin", name: "Darwin", born: 1809, died: 1882, field: "life", one: "Design without a designer." },
  { id: "kierkegaard", name: "Kierkegaard", born: 1813, died: 1855, field: "philosophy", one: "Truth is what you are willing to live." },
  { id: "riemann", name: "Riemann", born: 1826, died: 1866, field: "mathematics", one: "Geometry in any number of curved dimensions." },
  { id: "maxwell", name: "Maxwell", born: 1831, died: 1879, field: "physics", one: "Light is the field, shaking." },
  { id: "mach", name: "Mach", born: 1838, died: 1916, field: "physics", also: "philosophy", one: "Keep only what you can observe." },
  { id: "james", name: "William James", born: 1842, died: 1910, field: "psychology", also: "philosophy", one: "Consciousness is a stream, and truth is what works." },
  { id: "nietzsche", name: "Nietzsche", born: 1844, died: 1900, field: "philosophy", one: "Values have a history — and it is ours to write." },
  { id: "boltzmann", name: "Boltzmann", born: 1844, died: 1906, field: "physics", one: "Time's arrow is a counting argument." },
  { id: "cantor", name: "Cantor", born: 1845, died: 1918, field: "mathematics", one: "Some infinities are bigger than others." },
  { id: "freud", name: "Freud", born: 1856, died: 1939, field: "psychology", one: "You are not the master of your own house." },
  { id: "planck", name: "Planck", born: 1858, died: 1947, field: "physics", one: "Energy comes in lumps." },
  { id: "hilbert", name: "Hilbert", born: 1862, died: 1943, field: "mathematics", one: "Put all of mathematics on one proven footing." },
  { id: "adler", name: "Adler", born: 1870, died: 1937, field: "psychology", one: "The drive is not sex but significance." },
  { id: "russell", name: "Russell", born: 1872, died: 1970, field: "philosophy", also: "mathematics", one: "Logic as the skeleton of both." },
  { id: "jung", name: "Jung", born: 1875, died: 1961, field: "psychology", one: "Below the personal, a shared symbolic floor." },
  { id: "einstein", name: "Einstein", born: 1879, died: 1955, field: "physics", one: "Space and time bend; there is no universal now." },
  { id: "noether", name: "Emmy Noether", born: 1882, died: 1935, field: "mathematics", also: "physics", one: "Every symmetry hides a conservation law." },
  { id: "bohr", name: "Bohr", born: 1885, died: 1962, field: "physics", one: "Physics says what we can say about nature." },
  { id: "schrodinger", name: "Schrödinger", born: 1887, died: 1961, field: "physics", one: "The quantum as a wave — and a cat." },
  { id: "wittgenstein", name: "Wittgenstein", born: 1889, died: 1951, field: "philosophy", one: "Philosophy's problems are problems of language." },
  { id: "heidegger", name: "Heidegger", born: 1889, died: 1976, field: "philosophy", one: "Before knowing the world, we are already in it." },
  { id: "heisenberg", name: "Heisenberg", born: 1901, died: 1976, field: "physics", one: "Some questions cannot both be asked." },
  { id: "dirac", name: "Dirac", born: 1902, died: 1984, field: "physics", also: "mathematics", one: "Beauty in the equation, antimatter out of it." },
  { id: "godel", name: "Gödel", born: 1906, died: 1978, field: "mathematics", one: "Any system rich enough leaves truths it cannot prove." },
  { id: "sartre", name: "Sartre", born: 1905, died: 1980, field: "philosophy", one: "Existence first — you build the essence." },
  { id: "wheeler", name: "Wheeler", born: 1911, died: 2008, field: "physics", one: "Black hole, wormhole, it from bit." },
  { id: "turing", name: "Turing", born: 1912, died: 1954, field: "mathematics", one: "A machine that can imitate any machine." },
  { id: "camus", name: "Camus", born: 1913, died: 1960, field: "philosophy", one: "The absurd is not a reason to quit." },
  { id: "feynman", name: "Feynman", born: 1918, died: 1988, field: "physics", one: "Add up every path the particle could take." },
  { id: "penrose", name: "Penrose", born: 1931, died: 2100, field: "physics", also: "mathematics", one: "Singularities are unavoidable — and minds may be too strange for computers." },
  { id: "hawking", name: "Hawking", born: 1942, died: 2018, field: "physics", one: "Black holes are not black." },
  { id: "rovelli", name: "Rovelli", born: 1956, died: 2100, field: "physics", also: "philosophy", one: "There is no time — only relations between events." },
];

export const LINKS: Link[] = [
  // ancient
  { from: "thales", to: "pythagoras", kind: "read" },
  { from: "thales", to: "heraclitus", kind: "read" },
  { from: "pythagoras", to: "plato", kind: "read", note: "Number as the key to the real" },
  { from: "heraclitus", to: "parmenides", kind: "against", note: "Flux against being" },
  { from: "heraclitus", to: "plato", kind: "read" },
  { from: "parmenides", to: "plato", kind: "read" },
  { from: "parmenides", to: "democritus", kind: "against" },
  { from: "democritus", to: "epicurus", kind: "read" },
  { from: "socrates", to: "plato", kind: "taught" },
  { from: "plato", to: "aristotle", kind: "taught", note: "Twenty years at the Academy, then the break" },
  { from: "plato", to: "euclid", kind: "read" },
  { from: "aristotle", to: "ptolemy", kind: "read" },
  { from: "euclid", to: "archimedes", kind: "read" },
  { from: "euclid", to: "newton", kind: "read", note: "The Principia is written as geometry" },
  { from: "archimedes", to: "galileo", kind: "read" },
  { from: "ptolemy", to: "copernicus", kind: "against" },
  { from: "aristotle", to: "galileo", kind: "against", note: "The falling bodies" },
  { from: "aristotle", to: "darwin", kind: "read" },
  { from: "epicurus", to: "hume", kind: "read" },

  // revolution
  { from: "copernicus", to: "kepler", kind: "read" },
  { from: "copernicus", to: "galileo", kind: "read" },
  { from: "kepler", to: "newton", kind: "read" },
  { from: "galileo", to: "newton", kind: "read" },
  { from: "bacon", to: "newton", kind: "read" },
  { from: "bacon", to: "hume", kind: "read" },
  { from: "galileo", to: "descartes", kind: "with" },
  { from: "descartes", to: "spinoza", kind: "read" },
  { from: "descartes", to: "pascal", kind: "against" },
  { from: "descartes", to: "leibniz", kind: "read" },
  { from: "descartes", to: "newton", kind: "against" },
  { from: "spinoza", to: "einstein", kind: "read", note: "\"I believe in Spinoza's God\"" },
  { from: "spinoza", to: "hegel", kind: "read" },
  { from: "pascal", to: "kierkegaard", kind: "read" },
  { from: "newton", to: "leibniz", kind: "against", note: "The calculus priority war" },
  { from: "newton", to: "kant", kind: "read" },
  { from: "newton", to: "euler", kind: "read" },
  { from: "newton", to: "faraday", kind: "against" },
  { from: "leibniz", to: "euler", kind: "read" },
  { from: "leibniz", to: "russell", kind: "read" },
  { from: "leibniz", to: "turing", kind: "read" },
  { from: "leibniz", to: "rovelli", kind: "read", note: "Space as relation, not container" },

  // enlightenment onward
  { from: "hume", to: "kant", kind: "against", note: "\"He woke me from my dogmatic slumber\"" },
  { from: "hume", to: "darwin", kind: "read" },
  { from: "hume", to: "mach", kind: "read" },
  { from: "hume", to: "james", kind: "read" },
  { from: "kant", to: "hegel", kind: "read" },
  { from: "kant", to: "schopenhauer", kind: "read" },
  { from: "kant", to: "riemann", kind: "read" },
  { from: "kant", to: "einstein", kind: "against", note: "Space and time turn out not to be fixed forms" },
  { from: "hegel", to: "kierkegaard", kind: "against" },
  { from: "hegel", to: "nietzsche", kind: "against" },
  { from: "hegel", to: "sartre", kind: "read" },
  { from: "schopenhauer", to: "nietzsche", kind: "read" },
  { from: "schopenhauer", to: "freud", kind: "read" },
  { from: "schopenhauer", to: "wittgenstein", kind: "read" },
  { from: "euler", to: "gauss", kind: "read" },
  { from: "gauss", to: "riemann", kind: "taught" },
  { from: "riemann", to: "einstein", kind: "read", note: "The geometry general relativity needed" },
  { from: "riemann", to: "hilbert", kind: "read" },
  { from: "faraday", to: "maxwell", kind: "read", note: "Maxwell put Faraday's pictures into equations" },
  { from: "maxwell", to: "boltzmann", kind: "read" },
  { from: "maxwell", to: "einstein", kind: "read" },
  { from: "maxwell", to: "planck", kind: "read" },
  { from: "boltzmann", to: "planck", kind: "read" },
  { from: "boltzmann", to: "mach", kind: "against", note: "Do atoms exist, or only sensations?" },
  { from: "boltzmann", to: "rovelli", kind: "read", note: "Time as thermodynamics" },
  { from: "mach", to: "einstein", kind: "read" },
  { from: "mach", to: "james", kind: "with" },
  { from: "mach", to: "bohr", kind: "read" },
  { from: "mach", to: "heisenberg", kind: "read" },
  { from: "darwin", to: "james", kind: "read" },
  { from: "darwin", to: "freud", kind: "read" },
  { from: "darwin", to: "nietzsche", kind: "read" },
  { from: "kierkegaard", to: "heidegger", kind: "read" },
  { from: "kierkegaard", to: "camus", kind: "read" },
  { from: "nietzsche", to: "freud", kind: "read" },
  { from: "nietzsche", to: "jung", kind: "read" },
  { from: "nietzsche", to: "heidegger", kind: "read" },
  { from: "nietzsche", to: "camus", kind: "read" },
  { from: "nietzsche", to: "sartre", kind: "read" },
  { from: "james", to: "russell", kind: "with" },
  { from: "james", to: "jung", kind: "with" },
  { from: "james", to: "wittgenstein", kind: "read" },
  { from: "cantor", to: "hilbert", kind: "read" },
  { from: "cantor", to: "russell", kind: "read" },
  { from: "cantor", to: "godel", kind: "read" },
  { from: "freud", to: "adler", kind: "taught" },
  { from: "freud", to: "jung", kind: "taught", note: "Then the famous break" },
  { from: "freud", to: "sartre", kind: "against" },
  { from: "adler", to: "jung", kind: "with" },
  { from: "planck", to: "einstein", kind: "with" },
  { from: "planck", to: "bohr", kind: "read" },
  { from: "hilbert", to: "noether", kind: "with" },
  { from: "hilbert", to: "godel", kind: "against", note: "The programme and its limit" },
  { from: "hilbert", to: "einstein", kind: "with" },
  { from: "hilbert", to: "turing", kind: "read" },
  { from: "russell", to: "wittgenstein", kind: "taught" },
  { from: "russell", to: "godel", kind: "read" },
  { from: "einstein", to: "noether", kind: "with" },
  { from: "einstein", to: "bohr", kind: "against", note: "The Solvay debates" },
  { from: "einstein", to: "schrodinger", kind: "with" },
  { from: "einstein", to: "wheeler", kind: "read" },
  { from: "einstein", to: "penrose", kind: "read" },
  { from: "noether", to: "feynman", kind: "read" },
  { from: "bohr", to: "heisenberg", kind: "taught" },
  { from: "bohr", to: "dirac", kind: "read" },
  { from: "schrodinger", to: "heisenberg", kind: "against", note: "Waves against matrices" },
  { from: "schrodinger", to: "dirac", kind: "read" },
  { from: "heisenberg", to: "rovelli", kind: "read" },
  { from: "dirac", to: "feynman", kind: "read" },
  { from: "wittgenstein", to: "sartre", kind: "against" },
  { from: "heidegger", to: "sartre", kind: "read" },
  { from: "heidegger", to: "camus", kind: "read" },
  { from: "sartre", to: "camus", kind: "against", note: "The friendship that ended in print" },
  { from: "godel", to: "turing", kind: "read" },
  { from: "godel", to: "penrose", kind: "read" },
  { from: "turing", to: "penrose", kind: "against" },
  { from: "wheeler", to: "feynman", kind: "taught" },
  { from: "wheeler", to: "hawking", kind: "read" },
  { from: "wheeler", to: "rovelli", kind: "read" },
  { from: "feynman", to: "hawking", kind: "read" },
  { from: "feynman", to: "rovelli", kind: "read" },
  { from: "penrose", to: "hawking", kind: "with", note: "The singularity theorems" },
  { from: "penrose", to: "rovelli", kind: "read" },
  { from: "hawking", to: "rovelli", kind: "read" },
];
